"""Project-wide constants to avoid magic values."""

from __future__ import annotations

from domain.enums.timeframe import Timeframe

SUPPORTED_TIMEFRAMES: tuple[Timeframe, ...] = tuple(Timeframe)
DEFAULT_TIMEFRAME = Timeframe.H1

# API limits
DEFAULT_MAX_CONCURRENT_REQUESTS = 10
DEFAULT_FETCH_BATCH_SIZE = 1000
DEFAULT_RETRY_ATTEMPTS = 3
DEFAULT_RETRY_BACKOFF_SECONDS = 1.0

# Timeouts (seconds)
HTTP_TIMEOUT_SECONDS = 30
EXCHANGE_TIMEOUT_SECONDS = 20
COINGECKO_TIMEOUT_SECONDS = 20

# Trading defaults
DEFAULT_COMMISSION_RATE = 0.0004
DEFAULT_SLIPPAGE = 0.0005
DEFAULT_SPREAD = 0.0
TP1_CLOSE_RATIO = 0.5

# Strategy domain constants
STRATEGY_REQUIRED_COLUMNS = ("timestamp", "open", "high", "low", "close", "volume")
STRATEGY_MIN_LOOKBACK = 5
STRATEGY_MIN_LOOKBACK_BUFFER = 5
STRATEGY_MIN_VOLUME_MULT = 0.0
STRATEGY_MIN_RR = 0.0
STRATEGY_MIN_TP2_MULT = 1.0
STRATEGY_RISK_FLOOR = 0.002
STRATEGY_POSITION_SIZE = 1.0
STRATEGY_DEFAULT_OPEN_INTEREST = 0.0

# Reporting domain constants
REPORT_TRADES_COUNT_FILTER = 30
REPORT_PROFIT_FACTOR_FILTER = 1.0
REPORT_PROFITABLE_PF_THRESHOLD = 1.0
QUALITY_OI_MISSING_COLUMN_ISSUE = "oi_missing_column"
QUALITY_OI_ALIGNMENT_MISSING_VALUES_ISSUE = "oi_alignment_missing_values"
QUALITY_OI_ALIGNMENT_LEADING_GAPS_ISSUE = "oi_alignment_leading_gaps"
QUALITY_OI_ALIGNMENT_STALE_SERIES_ISSUE = "oi_alignment_stale_series"
QUALITY_SEVERITY_ERROR = "ERROR"
QUALITY_SEVERITY_WARNING = "WARNING"
QUALITY_SEVERITY_CRITICAL = "CRITICAL"
QUALITY_SEVERITY_INFO = "INFO"

# Backtest domain constants
BACKTEST_EMPTY_PF = 0.0
BACKTEST_EMPTY_PNL_PERCENT = 0.0
BACKTEST_EMPTY_WIN_RATE = 0.0
BACKTEST_EMPTY_MAX_DD = 0.0
BACKTEST_EMPTY_TRADES_COUNT = 0
BACKTEST_ZERO_COUNT = 0
BACKTEST_SORT_DESCENDING = False
BACKTEST_ROUND_METRICS = 4
BACKTEST_ROUND_MAX_DD = 6
BACKTEST_PF_FALLBACK_WHEN_NO_LOSSES = 99.0
BACKTEST_PROFITABLE_PF_THRESHOLD = 1.0

# Simulation/vectorbt domain constants
SIMULATION_VECTORBT_DIRECTION = "longonly"
SIMULATION_INIT_CASH = 100.0
SIMULATION_SIZE = 1.0
SIMULATION_SIZE_TYPE = "amount"
SIMULATION_FEES = 0.0
SIMULATION_SLIPPAGE = 0.0
SIMULATION_FREQ = "1min"
SIMULATION_PRICE_INIT = 100.0
SIMULATION_PNL_PERCENT_DIVISOR = 100.0
SIMULATION_DATETIME_UNIT_MS = "ms"
SIMULATION_TIMEZONE_UTC = "UTC"
SIMULATION_PARQUET_FILE_NAME = "data.parquet"

# Data quality thresholds
SPREAD_TO_CLOSE_WARNING_THRESHOLD = 0.3
OI_STALE_RATIO_THRESHOLD = 0.98

# Runtime defaults
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_TIMEZONE = "Europe/Belgrade"
DEFAULT_CACHE_DIR = "./cache"
DEFAULT_LOGS_DIR = "./logs"
DEFAULT_RESULTS_DIR = "./cache/results"
DEFAULT_BACKTEST_OUTPUT_FILE = "backtest_results.csv"
DEFAULT_REPORT_OUTPUT_FILE = "report.json"
DEFAULT_QUALITY_REPORT_OUTPUT_FILE = "quality_report.json"

# CLI defaults
DEFAULT_TOP_N = 50
DEFAULT_FETCH_DAYS = 60
DEFAULT_UPDATE_DAYS = 7

# Service defaults
FETCH_ALL_MAX_WORKERS = 2

# Error codes
ERROR_CODE_INVALID_CONFIG = "E_CFG_001"
ERROR_CODE_FETCH_FAILED = "E_FETCH_001"
ERROR_CODE_SIMULATION_FAILED = "E_SIM_001"
ERROR_CODE_DATA_QUALITY = "E_DQ_001"
ERROR_CODE_UNKNOWN = "E_UNKNOWN"
