from constants import (
    UNIVERSE_MIN_24H_USDT,
    UNIVERSE_MAX_SPREAD_BPS,
    UNIVERSE_MIN_TOP10_BID_USDT,
)


MIN_24H_USDT = UNIVERSE_MIN_24H_USDT
MAX_SPREAD_BPS = UNIVERSE_MAX_SPREAD_BPS
MIN_TOP10_BID_USDT = UNIVERSE_MIN_TOP10_BID_USDT


__all__ = ["MIN_24H_USDT", "MAX_SPREAD_BPS", "MIN_TOP10_BID_USDT"]
