VOLUME_THRESHOLD_USDT = 50_000_000
MIN_RR = 3
PROGRESS_RR_NEAR = 1
PROGRESS_RR_FAR = 3
MIN_SL_PCT = 0.003
MIN_TP_PCT = 0.010

IS_TRADING_ENABLED = True
POSITION_USDT = 10
MAX_TRADES_PER_HOUR = 3
MIN_COOLDOWN_PER_SYMBOL_MINUTES = 360  # 6 часов

SWING_PROXIMITY_ATR_MULTIPLIER = 1.2
STRONG_REACTION_VOLUME_MULTIPLIER = 1.2
MODERATE_REACTION_WICK_RATIO = 0.5
STRONG_REACTION_WICK_RATIO = 0.3
TP_LOOKAHEAD_BARS = 20
SL_LOOKBACK_BARS = 15
CANDLE_AVG_VOLUME_PERIOD = 20
TOUCH_DISTANCE_ATR = 1.5
FLAT_MAX_CENTER_SHIFT_ATR = 1.0