from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ArtifactSchema:
    name: str
    stage: str
    required_columns: tuple[str, ...]
    description: str

    def __post_init__(self) -> None:
        if not self.name.endswith((".csv", ".json")):
            raise ValueError("artifact name must include .csv or .json extension")
        if not self.stage:
            raise ValueError("stage is required")
        if len(set(self.required_columns)) != len(self.required_columns):
            raise ValueError(f"duplicate columns in artifact schema {self.name}")


MVP1_ARTIFACT_SCHEMAS: dict[str, ArtifactSchema] = {
    "anomaly_events.csv": ArtifactSchema(
        name="anomaly_events.csv",
        stage="mvp1_events",
        required_columns=(
            "event_id",
            "symbol",
            "state_time_ms",
            "event_start_time_ms",
            "minutes_since_start",
            "is_trigger",
            "event_detection_time_ms",
            "seed_time_ms",
            "seed_open",
            "seed_high",
            "seed_low",
            "seed_close",
            "initial_move_pct",
            "initial_volume_zscore",
            "initial_quote_volume_zscore",
            "initial_trade_count_zscore",
            "trigger_component",
            "trigger_components",
            "technical_noise_shock",
            "raw_candle_gap_minutes",
            "excluded_by_data_quality_gate",
            "daily_return_asof_t",
            "trade_count_market_percentile_asof_t",
            "detector_version",
        ),
        description="Anomaly event lifecycle trigger frame; detector output, not trade setups.",
    ),
    "anomaly_state_1m.csv": ArtifactSchema(
        name="anomaly_state_1m.csv",
        stage="mvp1_state",
        required_columns=(
            "event_id",
            "symbol",
            "state_time_ms",
            "snapshot_time_ms",
            "feature_cutoff_time_ms",
            "minutes_since_event_start",
            "minutes_since_detection",
            "event_alive",
            "running_high_asof_t",
            "running_high_time_asof_t_ms",
            "running_low_asof_t",
            "running_low_time_asof_t_ms",
            "time_since_running_high_minutes",
            "current_close",
            "current_return_from_start",
            "distance_to_running_high",
            "distance_to_running_low",
            "distance_to_structural_low",
            "distance_to_structural_high",
            "structural_low_asof_t",
            "structural_low_time_asof_t_ms",
            "structural_high_asof_t",
            "structural_high_time_asof_t_ms",
        ),
        description="Online 1m anomaly state using only data available as-of state_time.",
    ),
    "anomaly_future_paths.csv": ArtifactSchema(
        name="anomaly_future_paths.csv",
        stage="mvp1_future",
        required_columns=(
            "event_id",
            "symbol",
            "snapshot_time_ms",
            "feature_cutoff_time_ms",
            "future_start_time_ms",
            "atr_window_minutes",
            "ATR_1d_asof_t",
            "ATR_1d_pct_asof_t",
            "double_barrier_k_continuation",
            "double_barrier_k_fade",
            "future_return_5m",
            "future_return_15m",
            "future_return_30m",
            "future_return_60m",
            "future_return_120m",
            "future_return_180m",
            "future_max_5m",
            "future_max_15m",
            "future_max_30m",
            "future_max_60m",
            "future_max_120m",
            "future_max_180m",
            "future_min_5m",
            "future_min_15m",
            "future_min_30m",
            "future_min_60m",
            "future_min_120m",
            "future_min_180m",
            "future_return_atr_5m",
            "future_return_atr_15m",
            "future_return_atr_30m",
            "future_return_atr_60m",
            "future_return_atr_120m",
            "future_return_atr_180m",
            "future_max_atr_5m",
            "future_max_atr_15m",
            "future_max_atr_30m",
            "future_max_atr_60m",
            "future_max_atr_120m",
            "future_max_atr_180m",
            "future_min_atr_5m",
            "future_min_atr_15m",
            "future_min_atr_30m",
            "future_min_atr_60m",
            "future_min_atr_120m",
            "future_min_atr_180m",
            "intracandle_double_barrier_hit_5m",
            "intracandle_double_barrier_hit_15m",
            "intracandle_double_barrier_hit_30m",
            "intracandle_double_barrier_hit_60m",
            "intracandle_double_barrier_hit_120m",
            "intracandle_double_barrier_hit_180m",
            "barrier_resolution_5m",
            "barrier_resolution_15m",
            "barrier_resolution_30m",
            "barrier_resolution_60m",
            "barrier_resolution_120m",
            "barrier_resolution_180m",
            "reclaimed_running_high_30m",
            "reclaimed_running_high_60m",
            "broke_structural_low_30m",
            "broke_structural_low_60m",
            "time_to_new_high_minutes",
            "time_to_structural_break_minutes",
        ),
        description="Raw and ATR-normalized future paths strictly after each snapshot_time.",
    ),
    "anomaly_outcome_labels.csv": ArtifactSchema(
        name="anomaly_outcome_labels.csv",
        stage="mvp1_labels",
        required_columns=(
            "label_schema_version",
            "atr_window_minutes",
            "ATR_1d_asof_t",
            "k_continuation",
            "k_fade",
            "k_chop",
            "event_id",
            "symbol",
            "snapshot_time_ms",
            "feature_cutoff_time_ms",
            "future_start_time_ms",
            "scenario_15m",
            "scenario_30m",
            "scenario_60m",
            "scenario_120m",
            "scenario_180m",
            "label_available_15m",
            "label_available_30m",
            "label_available_60m",
            "label_available_120m",
            "label_available_180m",
            "label_source",
            "temporal_contract",
        ),
        description="MVP1 ATR-normalized 4-class future-nature scenario labels derived only from ATR-normalized future paths; not trading labels.",
    ),

    "anomaly_nature_atlas.csv": ArtifactSchema(
        name="anomaly_nature_atlas.csv",
        stage="mvp1_atlas",
        required_columns=(
            "atlas_version",
            "split_family",
            "split_value",
            "outcome_horizon_minutes",
            "atlas_outcome_bin",
            "outcome_coordinate",
            "row_count",
            "unique_event_count",
            "unique_symbol_count",
            "mean_future_return_atr",
            "median_future_return_atr",
            "mean_future_max_atr",
            "mean_future_min_atr",
            "mean_future_return",
            "median_future_return",
            "mean_future_max",
            "mean_future_min",
            "reclaim_rate",
            "double_barrier_stop_first_rate",
            "feature_min_snapshot_time_ms",
            "feature_max_snapshot_time_ms",
            "temporal_contract",
        ),
        description="Descriptive multi-horizon strategy nature atlas by as-of relative feature bins and ATR-normalized future response bins.",
    ),
    "anomaly_context_splits.csv": ArtifactSchema(
        name="anomaly_context_splits.csv",
        stage="mvp1_atlas",
        required_columns=(
            "atlas_version",
            "context_name",
            "context_value",
            "outcome_horizon_minutes",
            "outcome_coordinate",
            "row_count",
            "unique_event_count",
            "unique_symbol_count",
            "mean_minutes_since_trigger",
            "mean_current_return_from_start",
            "mean_distance_to_running_high_atr",
            "upside_continuation_share",
            "downside_extension_share",
            "two_sided_share",
            "range_chop_share",
            "mixed_drift_share",
            "missing_atr_future_share",
            "stop_first_barrier_share",
        ),
        description="Descriptive multi-horizon context splits; grouping columns are as-of feature/state bins and outcomes are ATR-normalized.",
    ),
    "anomaly_response_surfaces.csv": ArtifactSchema(
        name="anomaly_response_surfaces.csv",
        stage="mvp1_atlas",
        required_columns=(
            "atlas_version",
            "surface_name",
            "x_axis",
            "x_bin",
            "y_axis",
            "y_bin",
            "outcome_horizon_minutes",
            "outcome_coordinate",
            "row_count",
            "unique_event_count",
            "mean_future_return_atr",
            "mean_future_max_atr",
            "mean_future_min_atr",
            "reclaim_rate",
            "double_barrier_stop_first_rate",
            "dominant_outcome_bin",
        ),
        description="Descriptive multi-horizon response surfaces over relative/geometry feature bins and ATR-normalized future outcomes.",
    ),
    "anomaly_market_shock_groups.csv": ArtifactSchema(
        name="anomaly_market_shock_groups.csv",
        stage="mvp1_atlas",
        required_columns=(
            "atlas_version",
            "market_shock_group_id",
            "market_shock_id",
            "systemic_cluster_regime",
            "snapshot_time_ms",
            "outcome_horizon_minutes",
            "outcome_coordinate",
            "row_count",
            "unique_event_count",
            "unique_symbol_count",
            "simultaneous_anomalies_count_1m",
            "simultaneous_anomalies_share_1m",
            "symbols",
            "market_shock_candidate",
            "mean_current_return_from_start",
            "mean_future_return_atr",
            "dominant_outcome_bin",
            "temporal_contract",
        ),
        description="Multi-horizon market-shock groups keyed by point-in-time market_shock_id/systemic_cluster_regime.",
    ),
    "anomaly_oos_predictions.csv": ArtifactSchema(
        name="anomaly_oos_predictions.csv",
        stage="mvp1_prediction",
        required_columns=(
            "prediction_version",
            "strategy_name",
            "strategy_version",
            "strategy_contract_version",
            "target_label_column",
            "active_h_max_minutes",
            "event_id",
            "symbol",
            "snapshot_time_ms",
            "feature_cutoff_time_ms",
            "future_start_time_ms",
            "target_horizon_minutes",
            "target_scenario",
            "test_day",
            "train_cutoff_time_ms",
            "model_family",
            "model_key",
            "model_train_row_count",
            "model_group_row_count",
            "raw_p_long_continuation",
            "raw_p_short_fade",
            "raw_p_static_or_chop",
            "raw_p_unclear",
            "p_long_continuation",
            "p_short_fade",
            "p_static_or_chop",
            "p_unclear",
            "predicted_scenario",
            "prediction_confidence",
            "temporal_contract",
        ),
        description="Daily prequential OOS probabilities for descriptive future-nature scenarios; not decision or trade signals.",
    ),
    "anomaly_calibration.csv": ArtifactSchema(
        name="anomaly_calibration.csv",
        stage="mvp1_prediction",
        required_columns=(
            "prediction_version",
            "target_horizon_minutes",
            "predicted_scenario",
            "confidence_bucket",
            "row_count",
            "mean_confidence",
            "empirical_accuracy",
            "multiclass_brier",
            "log_loss",
        ),
        description="Reliability slices for OOS scenario probabilities by predicted class and confidence bucket.",
    ),
    "anomaly_calibration_breakdown.csv": ArtifactSchema(
        name="anomaly_calibration_breakdown.csv",
        stage="mvp1_prediction",
        required_columns=(
            "prediction_version",
            "target_horizon_minutes",
            "breakdown_name",
            "breakdown_value",
            "predicted_scenario",
            "confidence_bucket",
            "row_count",
            "mean_confidence",
            "empirical_accuracy",
            "multiclass_brier",
            "log_loss",
            "expected_calibration_error",
            "notes",
        ),
        description="OOS calibration reliability slices by session, week, month, symbol, systemic regime, market shock group, alpha decay, and trigger-age bucket.",
    ),
    "anomaly_prediction_metrics.csv": ArtifactSchema(
        name="anomaly_prediction_metrics.csv",
        stage="mvp1_prediction",
        required_columns=(
            "prediction_version",
            "target_horizon_minutes",
            "metric_name",
            "metric_value",
            "row_count",
            "notes",
        ),
        description="Aggregate OOS prediction metrics and protocol counters; not PnL or trading evaluation.",
    ),
    "strategy_model_metadata.csv": ArtifactSchema(
        name="strategy_model_metadata.csv",
        stage="mvp1_prediction",
        required_columns=(
            "prediction_version",
            "model_key",
            "model_family",
            "strategy_name",
            "strategy_version",
            "strategy_contract_version",
            "target_horizon_minutes",
            "target_label_column",
            "active_h_max_minutes",
            "weekly_model_freeze_time_ms",
            "train_cutoff_time_ms",
            "train_row_count",
            "fit_row_count",
            "validation_row_count",
            "calibration_row_count",
            "best_iteration",
            "class_order",
            "model_feature_names",
            "sample_weight_policy",
            "sample_weight_scope",
            "calibration_method",
        ),
        description="Frozen weekly model metadata including class order, feature names, and calibration method.",
    ),
    "strategy_feature_importance.csv": ArtifactSchema(
        name="strategy_feature_importance.csv",
        stage="mvp1_prediction",
        required_columns=(
            "prediction_version",
            "model_key",
            "feature_name",
            "feature_importance",
            "rank",
        ),
        description="CatBoost feature importance by frozen weekly model.",
    ),
    "strategy_model_training_diagnostics.csv": ArtifactSchema(
        name="strategy_model_training_diagnostics.csv",
        stage="mvp1_prediction",
        required_columns=(
            "prediction_version",
            "model_key",
            "test_week",
            "weekly_model_freeze_time_ms",
            "train_cutoff_time_ms",
            "train_row_count",
            "fit_row_count",
            "validation_row_count",
            "calibration_row_count",
            "fit_class_count",
            "validation_class_count",
            "calibration_class_count",
            "sample_weight_policy",
            "fit_sample_weight_sum",
            "validation_sample_weight_sum",
            "calibration_sample_weight_sum",
            "status",
            "reason",
        ),
        description="Weekly model training diagnostics and explicit skip reasons for non-silent empty OOS output.",
    ),

    "anomaly_decision_timing.csv": ArtifactSchema(
        name="anomaly_decision_timing.csv",
        stage="mvp1_decision",
        required_columns=(
            "ev_version",
            "strategy_name",
            "strategy_version",
            "event_id",
            "symbol",
            "state_time_ms",
            "snapshot_time_ms",
            "feature_cutoff_time_ms",
            "future_start_time_ms",
            "target_horizon_minutes",
            "execution_reference_model",
            "entry_price_basis",
            "entry_reference_price",
            "ATR_1d_asof_t",
            "execution_policy_version",
            "stop_policy_id",
            "target_policy_id",
            "stop_anchor",
            "target_anchor",
            "stop_trigger",
            "target_trigger",
            "stop_reference_price",
            "target_reference_price",
            "stop_distance",
            "target_distance",
            "execution_policy_resolved",
            "fee_bps",
            "slippage_bps",
            "cost_model",
            "cost_penalty",
            "p_follow_through_long",
            "p_adverse_long",
            "p_follow_through_short",
            "p_adverse_short",
            "confidence_calibrated",
            "RR_long_proxy",
            "RR_short_proxy",
            "RR_long_acceptable",
            "RR_short_acceptable",
            "selected_RR",
            "selected_RR_acceptable",
            "EV_long",
            "EV_short",
            "EV_wait",
            "EV_no_trade",
            "best_action",
            "is_prediction_confident",
            "is_RR_still_acceptable",
            "temporal_contract",
        ),
        description="Decision-timing rows with pre-simulation expected value from calibrated OOS probabilities, causal structural execution anchors, fees, and slippage; not realized PnL.",
    ),
    "anomaly_ev_metrics.csv": ArtifactSchema(
        name="anomaly_ev_metrics.csv",
        stage="mvp1_decision",
        required_columns=(
            "ev_version",
            "target_horizon_minutes",
            "metric_name",
            "metric_value",
            "row_count",
            "notes",
        ),
        description="Aggregate pre-simulation expected-value diagnostics; not trade simulation.",
    ),
    "anomaly_trade_simulation.csv": ArtifactSchema(
        name="anomaly_trade_simulation.csv",
        stage="mvp1_simulation",
        required_columns=(
            "simulation_version",
            "strategy_name",
            "strategy_version",
            "event_id",
            "symbol",
            "snapshot_time_ms",
            "feature_cutoff_time_ms",
            "target_horizon_minutes",
            "execution_reference_model",
            "entry_price_basis",
            "decision_action",
            "simulated_side",
            "entry_reference_time_ms",
            "entry_reference_open",
            "entry_price",
            "ATR_1d_asof_t",
            "execution_policy_version",
            "stop_policy_id",
            "target_policy_id",
            "stop_anchor",
            "target_anchor",
            "stop_trigger",
            "target_trigger",
            "target_close_fraction",
            "stop_distance",
            "target_distance",
            "stop_price",
            "final_stop_price",
            "target_price",
            "target_was_hit",
            "target_hit_time_ms",
            "fee_bps",
            "slippage_bps",
            "cost_model",
            "total_cost",
            "funding_cost",
            "exit_time_ms",
            "exit_price",
            "exit_reason",
            "gross_pnl",
            "net_pnl",
            "net_pnl_r",
            "net_return",
            "barrier_resolution",
            "temporal_contract",
        ),
        description="Structural-policy trade simulation rows with causal swing trailing and registered partial-close variants; not live execution.",
    ),
    "anomaly_trade_simulation_metrics.csv": ArtifactSchema(
        name="anomaly_trade_simulation_metrics.csv",
        stage="mvp1_simulation",
        required_columns=(
            "simulation_version",
            "target_horizon_minutes",
            "execution_variant_id",
            "stop_policy_id",
            "target_policy_id",
            "target_close_fraction",
            "metric_name",
            "metric_value",
            "row_count",
            "notes",
        ),
        description="Diagnostics scoped by declared structural execution variant; variant PnLs are never pooled as one portfolio.",
    ),


    "anomaly_placebo_tests.csv": ArtifactSchema(
        name="anomaly_placebo_tests.csv",
        stage="mvp1_controls",
        required_columns=(
            "control_version",
            "control_name",
            "target_horizon_minutes",
            "random_seed",
            "available_label_rows",
            "oos_prediction_rows",
            "accuracy",
            "multiclass_brier",
            "log_loss",
            "reference_real_brier",
            "brier_delta_vs_real",
            "status",
            "notes",
        ),
        description="Negative placebo tests for MVP1 prediction; shuffled targets are controls only, not scientific labels or trading signals.",
    ),
    "anomaly_baseline_comparison.csv": ArtifactSchema(
        name="anomaly_baseline_comparison.csv",
        stage="mvp1_controls",
        required_columns=(
            "control_version",
            "baseline_name",
            "feature_family",
            "target_horizon_minutes",
            "available_label_rows",
            "oos_prediction_rows",
            "accuracy",
            "multiclass_brier",
            "log_loss",
            "reference_real_brier",
            "brier_delta_vs_real",
            "status",
            "notes",
        ),
        description="Placebo, simple baseline, anomaly rule, and feature-ablation comparisons for MVP1 prediction; no EV, PnL, thresholds, or trade simulation.",
    ),

    "anomaly_feature_catalog.csv": ArtifactSchema(
        name="anomaly_feature_catalog.csv",
        stage="mvp1_features",
        required_columns=(
            "feature_schema_version",
            "feature_name",
            "feature_family",
            "source_artifact",
            "available_asof_time",
            "uses_future_data",
            "normalization_type",
            "is_model_feature",
            "is_audit_field",
            "missing_policy",
            "dtype",
            "description",
        ),
        description="Feature schema catalog enforcing as-of availability and relative-over-absolute model-feature rules.",
    ),
    "strategy_feature_schema.csv": ArtifactSchema(
        name="strategy_feature_schema.csv",
        stage="mvp1_features",
        required_columns=(
            "feature_schema_version",
            "feature_name",
            "feature_family",
            "source_artifact",
            "available_asof_time",
            "uses_future_data",
            "normalization_type",
            "is_model_feature",
            "is_audit_field",
            "missing_policy",
            "dtype",
            "description",
        ),
        description="Canonical strategy-neutral feature schema artifact for model feature contracts.",
    ),
    "strategy_registry.csv": ArtifactSchema(
        name="strategy_registry.csv",
        stage="mvp1_strategy_registry",
        required_columns=(
            "strategy_name",
            "strategy_version",
            "strategy_contract_version",
            "strategy_family",
            "horizon_minutes",
            "allowed_horizons",
            "default_horizon_minutes",
            "execution_policy_version",
            "execution_policy_ids",
            "feature_schema_version",
            "label_schema_version",
            "required_data_streams",
            "active_research_strategy",
            "live_trading_strategy",
        ),
        description="Registered strategy metadata exposed through the BaseStrategy contract, including selected, allowed, and default horizons.",
    ),
    "strategy_reject_reasons.csv": ArtifactSchema(
        name="strategy_reject_reasons.csv",
        stage="mvp1_strategy_registry",
        required_columns=(
            "strategy_name",
            "strategy_version",
            "reason_code",
            "owner_stage",
            "blocks_stage",
            "description",
        ),
        description="Explicit strategy reject-reason contract; no generic or silent rejects.",
    ),
    "strategy_implementation_status.csv": ArtifactSchema(
        name="strategy_implementation_status.csv",
        stage="mvp1_strategy_registry",
        required_columns=(
            "strategy_name",
            "strategy_family",
            "strategy_contract_version",
            "horizon_minutes",
            "allowed_horizons",
            "default_horizon_minutes",
            "implementation_status",
            "executable",
            "registry_error",
        ),
        description="Truth table for strategy variants: executable rows may be instantiated; specified-only rows must fail explicitly.",
    ),
    "anomaly_feature_matrix.csv": ArtifactSchema(
        name="anomaly_feature_matrix.csv",
        stage="mvp1_features",
        required_columns=(
            "feature_schema_version",
            "feature_matrix_version",
            "event_id",
            "symbol",
            "snapshot_time_ms",
            "feature_cutoff_time_ms",
            "minutes_since_trigger",
            "ATR_1d_asof_t",
            "ATR_1d_pct_asof_t",
            "current_return_from_start",
            "range_since_start_atr",
            "distance_to_running_high_atr",
            "distance_to_running_low_atr",
            "retracement_from_high_atr",
            "price_speed_atr",
            "clock_maturity",
            "event_age_ratio",
            "alpha_decay_bucket",
            "feature_source_status",
            "quote_volume_1m_to_24h_median",
            "volume_zscore",
            "quote_volume_zscore",
            "closed_5m_oi_asof_t",
            "oi_change_5m",
            "oi_change_10m",
            "oi_change_5m_pct_of_oi",
            "oi_change_10m_pct_of_oi",
            "missing_oi_flag",
            "short_liq_intensity",
            "long_liq_intensity",
            "liquidation_imbalance",
            "cumulative_liq_intensity_since_event_start",
            "missing_liquidation_flag",
            "cvd_quote_since_event_start",
            "cvd_change_3m",
            "cvd_change_5m",
            "cvd_change_10m",
            "cvd_price_divergence_3m",
            "cvd_price_divergence_5m",
            "cvd_price_divergence_10m",
            "price_up_cvd_down_flag",
            "price_down_cvd_up_flag",
            "cvd_failed_to_confirm_high_flag",
            "volume_market_percentile",
            "quote_volume_market_percentile",
            "return_1m_market_percentile",
            "return_from_event_market_percentile",
            "oi_growth_market_percentile",
            "liq_intensity_market_percentile",
            "range_expansion_market_percentile",
            "cross_section_available",
            "cross_section_symbol_count",
            "corr_with_btc_15m",
            "corr_with_btc_30m",
            "corr_with_btc_60m",
            "symbol_return_minus_btc_return_5m",
            "symbol_return_minus_btc_return_15m",
            "idiosyncratic_momentum_score",
            "simultaneous_anomalies_count_1m",
            "simultaneous_anomalies_share_1m",
            "systemic_cluster_regime",
            "market_shock_id",
            "initial_pump_height_core_atr_1440",
            "post_pump_consolidation_minutes",
            "consolidation_width_ratio",
            "shelf_low_asof_t",
            "shelf_high_asof_t",
            "current_low_minus_shelf_low_core_atr_1440",
            "current_close_minus_shelf_low_core_atr_1440",
            "current_high_minus_shelf_high_core_atr_1440",
            "minutes_spent_below_shelf",
            "minutes_since_reclaim",
            "volume_on_sweep_percentile",
            "trade_count_on_sweep_percentile",
            "cvd_change_during_sweep",
            "oi_change_during_sweep",
            "liq_intensity_during_sweep",
            "custom_features_json",
        ),
        description="As-of feature matrix for price path, speed-normalized time, volume, OI, liquidation, CVD, point-in-time cross-sectional, BTC-relative, systemic cluster, and relaxed anomaly geometry features; no future outcomes.",
    ),
    "anomaly_data_quality.csv": ArtifactSchema(
        name="anomaly_data_quality.csv",
        stage="mvp1_quality",
        required_columns=(
            "check_name",
            "status",
            "severity",
            "affected_rows",
            "message",
            "symbol",
            "timestamp_ms",
            "previous_timestamp_ms",
            "gap_minutes",
            "technical_noise_shock",
            "excluded_from_detector",
            "excluded_from_ml_dataset",
            "reason",
            "artifact",
        ),
        description="Data-quality checks; critical FAIL invalidates downstream interpretation.",
    ),
    "symbol_universe_by_day.csv": ArtifactSchema(
        name="symbol_universe_by_day.csv",
        stage="mvp1_universe",
        required_columns=(
            "trade_date",
            "symbol",
            "listed_asof_day",
            "delisted_asof_day",
            "tradable_on_day",
            "has_1m_data",
            "has_5m_data",
            "has_oi_data",
            "has_liquidation_data",
            "liquidity_eligible_on_day",
            "eligible_for_cross_section",
            "first_seen_data_time_ms",
            "last_seen_data_time_ms",
            "data_source_symbol_status",
            "listing_confidence",
            "delisting_confidence",
            "reason_if_excluded",
        ),
        description="Point-in-time symbol universe by day.",
    ),
    "research_ledger.csv": ArtifactSchema(
        name="research_ledger.csv",
        stage="mvp1_governance",
        required_columns=(
            "ledger_version",
            "protocol_freeze_id",
            "created_at_utc",
            "research_stage",
            "decision",
            "artifact",
            "rationale",
            "holdout_access_allowed_after_freeze",
            "final_holdout_start_date",
            "final_holdout_end_date",
        ),
        description="Research governance ledger for protocol freeze and holdout access decisions.",
    ),
    "holdout_access_log.csv": ArtifactSchema(
        name="holdout_access_log.csv",
        stage="mvp1_governance",
        required_columns=(
            "access_id",
            "protocol_freeze_id",
            "accessed_at_utc",
            "actor",
            "reason",
            "artifact",
            "final_holdout_start_date",
            "final_holdout_end_date",
            "access_approved",
        ),
        description="Explicit final-holdout access log; empty before first approved holdout read.",
    ),

    "anomaly_rejection_funnel.csv": ArtifactSchema(
        name="anomaly_rejection_funnel.csv",
        stage="mvp1_rejection_funnel",
        required_columns=(
            "funnel_version",
            "run_id",
            "strategy_name",
            "strategy_version",
            "strategy_contract_version",
            "target_horizon_minutes",
            "stage",
            "source_artifact",
            "row_key",
            "event_id",
            "symbol",
            "snapshot_time_ms",
            "status",
            "reason_code",
            "reason_detail",
            "upstream_stage",
            "downstream_stage",
            "row_count",
            "temporal_contract",
        ),
        description="Artifact-driven row lineage and rejection funnel across data quality, universe, trigger, state, future, labels, prediction, decision, and simulation stages.",
    ),
    "anomaly_protocol_audit.csv": ArtifactSchema(
        name="anomaly_protocol_audit.csv",
        stage="mvp1_audit",
        required_columns=("check_name", "status", "message", "artifact"),
        description="Protocol audit for temporal correctness and anti-leakage invariants.",
    ),
    "anomaly_run_config.csv": ArtifactSchema(
        name="anomaly_run_config.csv",
        stage="mvp1_config",
        required_columns=("key", "value", "source"),
        description="Run configuration and reproducibility metadata.",
    ),
    "anomaly_stage_timings.csv": ArtifactSchema(
        name="anomaly_stage_timings.csv",
        stage="run_research",
        required_columns=("stage_name", "status", "started_at_utc", "finished_at_utc", "duration_seconds", "notes"),
        description="Per-stage run-research wall-clock timings written incrementally for bottleneck diagnosis.",
    ),
    "anomaly_resource_usage.csv": ArtifactSchema(
        name="anomaly_resource_usage.csv",
        stage="run_research",
        required_columns=(
            "stage_name",
            "status",
            "started_at_utc",
            "finished_at_utc",
            "duration_seconds",
            "progress_done",
            "progress_total",
            "progress_unit",
            "process_rss_mb",
            "run_dir_size_mb",
            "run_dir_file_count",
            "largest_files",
            "notes",
        ),
        description="Per-stage run-research process RSS and run-dir growth written incrementally for memory/IO diagnosis.",
    ),
    "strategy_custom_feature_schema.csv": ArtifactSchema(
        name="strategy_custom_feature_schema.csv",
        stage="mvp1_features",
        required_columns=(
            "strategy_name",
            "feature_schema_version",
            "feature_name",
            "feature_family",
            "dtype",
            "is_model_feature",
            "required_streams",
            "identifiability",
            "description",
        ),
        description="Strategy-owned causal feature declarations materialized through BaseStrategy rather than hard-coded Core branches.",
    ),
    "anomaly_archetype_catalog.csv": ArtifactSchema(
        name="anomaly_archetype_catalog.csv",
        stage="archetype_discovery",
        required_columns=(
            "category_id",
            "status",
            "evidence_mode",
            "protocol_freeze_id",
            "tree_index",
            "leaf_index",
            "generator_seed",
            "generator_depth",
            "origin_fraction",
            "origin_support_count",
            "origin_support_fraction",
            "generator_support_count",
            "generator_support_fraction",
            "rule_text",
            "rule_json",
            "feature_names",
            "discovery_event_count",
            "discovery_fade_count",
            "discovery_matched_event_count",
            "discovery_unique_event_fraction",
            "discovery_inference_block_count",
            "discovery_fade_rate",
            "discovery_global_blind_rate",
            "discovery_matched_blind_rate",
            "discovery_lift",
            "discovery_cluster_lower_95",
            "discovery_cluster_edge_lower_95",
            "verification_event_count",
            "verification_fade_count",
            "verification_matched_event_count",
            "verification_inference_block_count",
            "verification_fade_rate",
            "verification_global_blind_rate",
            "verification_matched_blind_rate",
            "verification_lift",
            "verification_cluster_lower_95",
            "verification_cluster_edge_lower_95",
            "verification_p_value",
            "verification_q_value",
            "verification_stability_periods",
            "verification_positive_period_fraction",
            "first_signal_policy",
            "temporal_contract",
        ),
        description="Frozen CatBoost tree-path archetypes with discovery and later temporal-verification evidence.",
    ),
    "anomaly_archetype_controls.csv": ArtifactSchema(
        name="anomaly_archetype_controls.csv",
        stage="archetype_discovery",
        required_columns=(
            "control_name",
            "random_seed",
            "discovery_event_count",
            "verification_event_count",
            "discovery_blind_rate",
            "verification_blind_rate",
            "verification_auc",
            "discovery_candidate_count",
            "distinct_candidate_count",
            "verified_category_count",
            "shuffled_row_fraction",
            "notes",
        ),
        description="Blind and whole-anomaly shuffled-label controls for archetype discovery.",
    ),
    "anomaly_archetype_coverage.csv": ArtifactSchema(
        name="anomaly_archetype_coverage.csv",
        stage="archetype_discovery",
        required_columns=(
            "split",
            "total_event_count",
            "first_signal_fade_event_count",
            "covered_event_count",
            "covered_first_signal_fade_event_count",
            "overlapping_event_count",
            "unclassified_event_count",
            "covered_fraction",
            "covered_first_signal_fade_fraction",
            "unclassified_first_signal_fade_rate",
            "accepted_category_count",
            "generated_candidate_count",
            "distinct_candidate_count",
            "registered_generator_count",
            "rolling_origin_count",
            "search_truncated",
            "controls_passed",
            "claim_scope",
        ),
        description="Coverage and explicit unclassified remainder for the registered predictive-phenotype search space.",
    ),
    "anomaly_archetype_candidate_funnel.csv": ArtifactSchema(
        name="anomaly_archetype_candidate_funnel.csv",
        stage="archetype_discovery",
        required_columns=("stage", "candidate_count", "notes"),
        description="Real-label candidate counts remaining after each pre-registered discovery and verification gate.",
    ),
    "artifact_manifest.json": ArtifactSchema(
        name="artifact_manifest.json",
        stage="all",
        required_columns=("run_id", "created_at_utc", "artifacts"),
        description="Machine-readable manifest for artifacts written by a run.",
    ),
}


STRATEGY_ARTIFACT_ALIASES: dict[str, str] = {
    "anomaly_events.csv": "strategy_events.csv",
    "anomaly_state_1m.csv": "strategy_state_1m.csv",
    "anomaly_future_paths.csv": "strategy_future_paths.csv",
    "anomaly_outcome_labels.csv": "strategy_outcome_labels.csv",
    "anomaly_feature_catalog.csv": "strategy_feature_catalog.csv",
    "anomaly_feature_matrix.csv": "strategy_feature_matrix.csv",
    "anomaly_nature_atlas.csv": "strategy_nature_atlas.csv",
    "anomaly_context_splits.csv": "strategy_context_splits.csv",
    "anomaly_response_surfaces.csv": "strategy_response_surfaces.csv",
    "anomaly_market_shock_groups.csv": "strategy_market_shock_groups.csv",
    "anomaly_oos_predictions.csv": "strategy_oos_predictions.csv",
    "anomaly_calibration.csv": "strategy_calibration.csv",
    "anomaly_calibration_breakdown.csv": "strategy_calibration_breakdown.csv",
    "anomaly_prediction_metrics.csv": "strategy_prediction_metrics.csv",
    "anomaly_decision_timing.csv": "strategy_decision_timing.csv",
    "anomaly_ev_metrics.csv": "strategy_ev_metrics.csv",
    "anomaly_trade_simulation.csv": "strategy_trade_simulation.csv",
    "anomaly_trade_simulation_metrics.csv": "strategy_trade_simulation_metrics.csv",
    "anomaly_placebo_tests.csv": "strategy_placebo_tests.csv",
    "anomaly_baseline_comparison.csv": "strategy_baseline_comparison.csv",
    "anomaly_data_quality.csv": "strategy_data_quality.csv",
    "anomaly_rejection_funnel.csv": "strategy_rejection_funnel.csv",
    "anomaly_protocol_audit.csv": "strategy_protocol_audit.csv",
    "anomaly_run_config.csv": "strategy_run_config.csv",
    "anomaly_stage_timings.csv": "strategy_stage_timings.csv",
    "anomaly_resource_usage.csv": "strategy_resource_usage.csv",
    "anomaly_archetype_catalog.csv": "strategy_archetype_catalog.csv",
    "anomaly_archetype_controls.csv": "strategy_archetype_controls.csv",
    "anomaly_archetype_coverage.csv": "strategy_archetype_coverage.csv",
    "anomaly_archetype_candidate_funnel.csv": "strategy_archetype_candidate_funnel.csv",
}


HEAVY_STRATEGY_ARTIFACT_ALIASES: frozenset[tuple[str, str]] = frozenset(
    {
        ("anomaly_state_1m.csv", "strategy_state_1m.csv"),
        ("anomaly_future_paths.csv", "strategy_future_paths.csv"),
        ("anomaly_feature_matrix.csv", "strategy_feature_matrix.csv"),
    }
)


def is_heavy_strategy_artifact_alias_pair(left_name: str, right_name: str) -> bool:
    """Return true for compatibility aliases that must not be materialized as huge files."""
    return (left_name, right_name) in HEAVY_STRATEGY_ARTIFACT_ALIASES or (
        right_name, left_name
    ) in HEAVY_STRATEGY_ARTIFACT_ALIASES


def should_materialize_strategy_artifact_alias(source_name: str, alias_name: str) -> bool:
    """Keep lightweight CSV aliases, but skip historical/state/feature heavy duplicates."""
    return not is_heavy_strategy_artifact_alias_pair(source_name, alias_name)


for source_name, alias_name in STRATEGY_ARTIFACT_ALIASES.items():
    source_schema = MVP1_ARTIFACT_SCHEMAS[source_name]
    MVP1_ARTIFACT_SCHEMAS[alias_name] = ArtifactSchema(
        name=alias_name,
        stage=source_schema.stage,
        required_columns=source_schema.required_columns,
        description=f"Strategy-neutral canonical artifact for {source_name}. {source_schema.description}",
    )


_ANOMALY_ARTIFACT_BY_STRATEGY_NAME = {strategy_name: anomaly_name for anomaly_name, strategy_name in STRATEGY_ARTIFACT_ALIASES.items()}


def get_strategy_artifact_alias(name: str) -> str | None:
    return STRATEGY_ARTIFACT_ALIASES.get(name)


def get_strategy_artifact_companion_names(name: str) -> tuple[str, ...]:
    strategy_name = STRATEGY_ARTIFACT_ALIASES.get(name)
    if strategy_name is not None:
        return (strategy_name,)
    anomaly_name = _ANOMALY_ARTIFACT_BY_STRATEGY_NAME.get(name)
    if anomaly_name is not None:
        return (anomaly_name,)
    return ()


def get_artifact_schema(name: str) -> ArtifactSchema:
    try:
        return MVP1_ARTIFACT_SCHEMAS[name]
    except KeyError as exc:
        raise KeyError(f"unknown MVP1 artifact schema: {name}") from exc
