from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ArtifactSchema:
    name: str
    stage: str
    required_columns: tuple[str, ...]
    description: str

    def __post_init__(self) -> None:
        if not self.name.endswith((".csv", ".json")):
            raise ValueError("artifact name must include .csv or .json extension")
        if not self.stage:
            raise ValueError("stage is required")
        if len(set(self.required_columns)) != len(self.required_columns):
            raise ValueError(f"duplicate columns in artifact schema {self.name}")


MVP1_ARTIFACT_SCHEMAS: dict[str, ArtifactSchema] = {
    "anomaly_events.csv": ArtifactSchema(
        name="anomaly_events.csv",
        stage="mvp1_events",
        required_columns=(
            "event_id",
            "symbol",
            "event_start_time_ms",
            "event_detection_time_ms",
            "seed_time_ms",
            "seed_open",
            "seed_high",
            "seed_low",
            "seed_close",
            "initial_move_pct",
            "initial_volume_zscore",
            "initial_quote_volume_zscore",
            "initial_trade_count_zscore",
            "technical_noise_shock",
            "raw_candle_gap_minutes",
            "excluded_by_data_quality_gate",
            "detector_version",
        ),
        description="Broad anomaly events; detector output, not trade setups.",
    ),
    "anomaly_state_1m.csv": ArtifactSchema(
        name="anomaly_state_1m.csv",
        stage="mvp1_state",
        required_columns=(
            "event_id",
            "symbol",
            "state_time_ms",
            "snapshot_time_ms",
            "feature_cutoff_time_ms",
            "minutes_since_event_start",
            "minutes_since_detection",
            "event_alive",
            "running_high_asof_t",
            "running_high_time_asof_t_ms",
            "running_low_asof_t",
            "running_low_time_asof_t_ms",
            "time_since_running_high_minutes",
            "current_close",
            "current_return_from_start",
            "distance_to_running_high",
            "distance_to_running_low",
            "distance_to_structural_low",
            "distance_to_structural_high",
        ),
        description="Online 1m anomaly state using only data available as-of state_time.",
    ),
    "anomaly_future_paths.csv": ArtifactSchema(
        name="anomaly_future_paths.csv",
        stage="mvp1_future",
        required_columns=(
            "event_id",
            "symbol",
            "snapshot_time_ms",
            "feature_cutoff_time_ms",
            "future_start_time_ms",
            "atr_window_minutes",
            "ATR_1d_asof_t",
            "ATR_1d_pct_asof_t",
            "future_return_5m",
            "future_return_15m",
            "future_return_30m",
            "future_return_60m",
            "future_return_120m",
            "future_max_5m",
            "future_max_15m",
            "future_max_30m",
            "future_max_60m",
            "future_max_120m",
            "future_min_5m",
            "future_min_15m",
            "future_min_30m",
            "future_min_60m",
            "future_min_120m",
            "future_return_atr_5m",
            "future_return_atr_15m",
            "future_return_atr_30m",
            "future_return_atr_60m",
            "future_return_atr_120m",
            "future_max_atr_5m",
            "future_max_atr_15m",
            "future_max_atr_30m",
            "future_max_atr_60m",
            "future_max_atr_120m",
            "future_min_atr_5m",
            "future_min_atr_15m",
            "future_min_atr_30m",
            "future_min_atr_60m",
            "future_min_atr_120m",
            "reclaimed_running_high_30m",
            "reclaimed_running_high_60m",
            "broke_structural_low_30m",
            "broke_structural_low_60m",
            "time_to_new_high_minutes",
            "time_to_structural_break_minutes",
        ),
        description="Raw and ATR-normalized future paths strictly after each snapshot_time.",
    ),
    "anomaly_outcome_labels.csv": ArtifactSchema(
        name="anomaly_outcome_labels.csv",
        stage="mvp1_labels",
        required_columns=(
            "label_policy_version",
            "event_id",
            "symbol",
            "snapshot_time_ms",
            "feature_cutoff_time_ms",
            "future_start_time_ms",
            "scenario_15m",
            "scenario_30m",
            "scenario_60m",
            "label_available_15m",
            "label_available_30m",
            "label_available_60m",
            "label_source",
            "temporal_contract",
        ),
        description="MVP1 descriptive future-nature scenario labels derived only from raw future paths; not trading labels.",
    ),

    "anomaly_nature_atlas.csv": ArtifactSchema(
        name="anomaly_nature_atlas.csv",
        stage="mvp1_atlas",
        required_columns=(
            "atlas_version",
            "split_family",
            "split_value",
            "outcome_horizon_minutes",
            "atlas_outcome_bin",
            "row_count",
            "unique_event_count",
            "unique_symbol_count",
            "mean_future_return",
            "median_future_return",
            "mean_future_max",
            "mean_future_min",
            "reclaim_rate",
            "feature_min_snapshot_time_ms",
            "feature_max_snapshot_time_ms",
            "temporal_contract",
        ),
        description="Descriptive anomaly nature atlas by state-only context bins and coarse future response bins.",
    ),
    "anomaly_context_splits.csv": ArtifactSchema(
        name="anomaly_context_splits.csv",
        stage="mvp1_atlas",
        required_columns=(
            "atlas_version",
            "context_name",
            "context_value",
            "row_count",
            "unique_event_count",
            "unique_symbol_count",
            "mean_minutes_since_detection",
            "mean_current_return_from_start",
            "mean_distance_to_running_high",
            "upside_continuation_share",
            "downside_extension_share",
            "two_sided_share",
            "range_chop_share",
            "mixed_drift_share",
            "missing_future_share",
        ),
        description="Descriptive context splits; grouping columns are state-only and as-of snapshot time.",
    ),
    "anomaly_response_surfaces.csv": ArtifactSchema(
        name="anomaly_response_surfaces.csv",
        stage="mvp1_atlas",
        required_columns=(
            "atlas_version",
            "surface_name",
            "x_axis",
            "x_bin",
            "y_axis",
            "y_bin",
            "outcome_horizon_minutes",
            "row_count",
            "unique_event_count",
            "mean_future_return",
            "mean_future_max",
            "mean_future_min",
            "reclaim_rate",
            "dominant_outcome_bin",
        ),
        description="Simple descriptive response surfaces over state-only atlas bins.",
    ),
    "anomaly_market_shock_groups.csv": ArtifactSchema(
        name="anomaly_market_shock_groups.csv",
        stage="mvp1_atlas",
        required_columns=(
            "atlas_version",
            "market_shock_group_id",
            "snapshot_time_ms",
            "row_count",
            "unique_event_count",
            "unique_symbol_count",
            "symbols",
            "market_shock_candidate",
            "mean_current_return_from_start",
            "mean_future_return_30m",
            "dominant_outcome_bin",
            "temporal_contract",
        ),
        description="Coarse simultaneous-snapshot groups; no market-beta inference or independence claim.",
    ),
    "anomaly_oos_predictions.csv": ArtifactSchema(
        name="anomaly_oos_predictions.csv",
        stage="mvp1_prediction",
        required_columns=(
            "prediction_version",
            "event_id",
            "symbol",
            "snapshot_time_ms",
            "feature_cutoff_time_ms",
            "future_start_time_ms",
            "target_horizon_minutes",
            "target_scenario",
            "test_day",
            "train_cutoff_time_ms",
            "model_family",
            "model_key",
            "model_train_row_count",
            "model_group_row_count",
            "p_long_continuation",
            "p_short_fade",
            "p_static_or_chop",
            "p_trap",
            "p_unclear",
            "predicted_scenario",
            "prediction_confidence",
            "temporal_contract",
        ),
        description="Daily prequential OOS probabilities for descriptive future-nature scenarios; not decision or trade signals.",
    ),
    "anomaly_calibration.csv": ArtifactSchema(
        name="anomaly_calibration.csv",
        stage="mvp1_prediction",
        required_columns=(
            "prediction_version",
            "target_horizon_minutes",
            "predicted_scenario",
            "confidence_bucket",
            "row_count",
            "mean_confidence",
            "empirical_accuracy",
            "multiclass_brier",
            "log_loss",
        ),
        description="Reliability slices for OOS scenario probabilities by predicted class and confidence bucket.",
    ),
    "anomaly_prediction_metrics.csv": ArtifactSchema(
        name="anomaly_prediction_metrics.csv",
        stage="mvp1_prediction",
        required_columns=(
            "prediction_version",
            "target_horizon_minutes",
            "metric_name",
            "metric_value",
            "row_count",
            "notes",
        ),
        description="Aggregate OOS prediction metrics and protocol counters; not PnL or trading evaluation.",
    ),


    "anomaly_placebo_tests.csv": ArtifactSchema(
        name="anomaly_placebo_tests.csv",
        stage="mvp1_controls",
        required_columns=(
            "control_version",
            "control_name",
            "target_horizon_minutes",
            "random_seed",
            "available_label_rows",
            "oos_prediction_rows",
            "accuracy",
            "multiclass_brier",
            "log_loss",
            "reference_real_brier",
            "brier_delta_vs_real",
            "status",
            "notes",
        ),
        description="Negative placebo tests for MVP1 prediction; shuffled targets are controls only, not scientific labels or trading signals.",
    ),
    "anomaly_baseline_comparison.csv": ArtifactSchema(
        name="anomaly_baseline_comparison.csv",
        stage="mvp1_controls",
        required_columns=(
            "control_version",
            "baseline_name",
            "feature_family",
            "target_horizon_minutes",
            "available_label_rows",
            "oos_prediction_rows",
            "accuracy",
            "multiclass_brier",
            "log_loss",
            "reference_real_brier",
            "brier_delta_vs_real",
            "status",
            "notes",
        ),
        description="Simple baseline comparison for MVP1 prediction; no EV, PnL, thresholds, or trade simulation.",
    ),

    "anomaly_feature_catalog.csv": ArtifactSchema(
        name="anomaly_feature_catalog.csv",
        stage="mvp1_features",
        required_columns=(
            "feature_name",
            "family",
            "dtype",
            "description",
            "availability_rule",
            "uses_future_data",
            "nullable",
        ),
        description="Feature schema catalog and availability rules.",
    ),
    "anomaly_data_quality.csv": ArtifactSchema(
        name="anomaly_data_quality.csv",
        stage="mvp1_quality",
        required_columns=(
            "check_name",
            "status",
            "severity",
            "affected_rows",
            "message",
            "symbol",
            "timestamp_ms",
            "previous_timestamp_ms",
            "gap_minutes",
            "technical_noise_shock",
            "excluded_from_detector",
            "excluded_from_ml_dataset",
            "reason",
            "artifact",
        ),
        description="Data-quality checks; critical FAIL invalidates downstream interpretation.",
    ),
    "symbol_universe_by_day.csv": ArtifactSchema(
        name="symbol_universe_by_day.csv",
        stage="mvp1_universe",
        required_columns=(
            "trade_date",
            "symbol",
            "listed_asof_day",
            "delisted_asof_day",
            "tradable_on_day",
            "has_1m_data",
            "has_5m_data",
            "has_oi_data",
            "has_liquidation_data",
            "liquidity_eligible_on_day",
            "reason_if_excluded",
        ),
        description="Point-in-time symbol universe by day.",
    ),
    "anomaly_protocol_audit.csv": ArtifactSchema(
        name="anomaly_protocol_audit.csv",
        stage="mvp1_audit",
        required_columns=("check_name", "status", "message", "artifact"),
        description="Protocol audit for temporal correctness and anti-leakage invariants.",
    ),
    "anomaly_run_config.csv": ArtifactSchema(
        name="anomaly_run_config.csv",
        stage="mvp1_config",
        required_columns=("key", "value", "source"),
        description="Run configuration and reproducibility metadata.",
    ),
    "artifact_manifest.json": ArtifactSchema(
        name="artifact_manifest.json",
        stage="all",
        required_columns=("run_id", "created_at_utc", "artifacts"),
        description="Machine-readable manifest for artifacts written by a run.",
    ),
}


def get_artifact_schema(name: str) -> ArtifactSchema:
    try:
        return MVP1_ARTIFACT_SCHEMAS[name]
    except KeyError as exc:
        raise KeyError(f"unknown MVP1 artifact schema: {name}") from exc
